[package]
name = "virival-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "=0.8.4", features = ["json"] }
chrono = { version = "=0.4.38", features = ["serde"] }
serde = { version = "=1.0.215", features = ["derive"] }
serde_json = "=1.0.133"
thiserror = "=1.0.64"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "=0.6.2", features = ["trace"] }
tracing = "=0.1.40"
tracing-subscriber = { version = "=0.3.18", features = ["env-filter", "fmt"] }
uuid = { version = "=1.8.0", features = ["serde", "v4"] }
dotenvy = "=0.15.7"
async-trait = "=0.1.83"
deadpool-postgres = "=0.14.1"
tokio-postgres = { version = "=0.7.13", features = ["with-uuid-1", "with-chrono-0_4"] }
postgres-protocol = "=0.6.10"
postgres-types = "=0.2.12"
